title: Jack's Blog
subtitle: jtchen0528
description: engineer

author: Jhao-Ting (Jack) Chen
email: jtchen0528@outlook.com
avatar: assets/images/avatar.jpg

baseurl: "/blog"
url: "https://jtchen0528.github.io"

# Social settings
facebook_url: https://www.facebook.com/jtchen0528
instagram_url: https://www.instagram.com/jtchen0528
github_url: https://github.com/jtchen0528
linkedin_url: https://www.linkedin.com/in/jtchen0528/
email: jtchen0528@gmail.com


# Build settings
remote_theme: chrisbobbe/jekyll-theme-prologue
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Necessary for Prologue theme:
collections: [sections]

google_analytics: G-6VE995W3K8